    package com.example.datn.core.admin.discountDetail.service.Impl;

   import com.example.datn.core.admin.discountDetail.model.DiscountDetailResponse;
    import com.example.datn.core.admin.discountDetail.repository.ADDiscountDetailRepository;
    import com.example.datn.core.admin.discountDetail.service.DiscountDetailService;
    import com.example.datn.entity.Discount;
    import com.example.datn.entity.DiscountDetail;
    import com.example.datn.entity.ProductDetail;
    import com.example.datn.repository.ProductDetailRepository; // Giả định bạn đã có Repo này
    import com.example.datn.utils.DataGeneratorUtils;
    import org.springframework.beans.factory.annotation.Autowired;
    import org.springframework.stereotype.Service;
    import org.springframework.transaction.annotation.Transactional;

    import java.math.BigDecimal;
    import java.util.List;
    import java.util.UUID;
    import java.util.stream.Collectors;

    @Service
    public class DiscountDetailServiceImpl implements DiscountDetailService {

        @Autowired
        private ADDiscountDetailRepository adDiscountDetailRepository;

        @Autowired
        private ProductDetailRepository productDetailRepository;

        @Override
        public List<DiscountDetailResponse> getByIdDiscount(String idDiscount) {
            return adDiscountDetailRepository.findAllByDiscountId(idDiscount)
                    .stream()
                    .map(DiscountDetailResponse::new)
                    .collect(Collectors.toList());
        }

        @Override
        @Transactional
        public void saveAll(Discount discount, List<String> productDetailIds) {
            adDiscountDetailRepository.deleteByDiscountId(discount.getId());

            if (productDetailIds != null && !productDetailIds.isEmpty()) {
                // Tạo danh sách tạm để chứa các chi tiết
                List<DiscountDetail> detailsToSave = new java.util.ArrayList<>();

                for (String pdId : productDetailIds) {
                    ProductDetail pd = productDetailRepository.findById(pdId)
                            .orElseThrow(() -> new RuntimeException("Không tìm thấy sản phẩm: " + pdId));

                    DiscountDetail detail = new DiscountDetail();
                    String autoGeneratedCode = DataGeneratorUtils.generateRandomCode("DD-");
                    detail.setId(UUID.randomUUID().toString());
                    detail.setCode(autoGeneratedCode);
                    detail.setDiscount(discount);
                    detail.setProductDetail(pd);
                    detail.setPriceBefore(pd.getSalePrice());
                    detail.setPriceAfter(calculatePriceAfter(pd.getSalePrice(), discount.getDiscountPercent()));
                    detail.setStatus(1);
                    detailsToSave.add(detail);
                }
                // Lưu tất cả cùng một lúc
                adDiscountDetailRepository.saveAll(detailsToSave);
            }
        }

        private BigDecimal calculatePriceAfter(BigDecimal originalPrice, BigDecimal discountPercent) {
            BigDecimal discountFactor = BigDecimal.valueOf(100).subtract(discountPercent);
            // Thêm RoundingMode.HALF_UP để làm tròn số tiền một cách an toàn
            return originalPrice.multiply(discountFactor)
                    .divide(BigDecimal.valueOf(100), 0, java.math.RoundingMode.HALF_UP);
        }
    }
