services:
  db:
    image: mysql:8.4 # Bản LTS ổn định cho dự án Java của bạn
    container_name: msi_mysql_bind
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 281003
      MYSQL_DATABASE: datn
      TZ: Asia/Ho_Chi_Minh  # <--- Bổ sung múi giờ cho MySQL
    ports:
      - "3307:3306"
    volumes:
      # BIND MOUNT: [Đường dẫn máy MSI] : [Đường dẫn trong Container]
      - ./mysql_data:/var/lib/mysql
      - ./mysql_config:/etc/mysql/conf.d
      # (Tùy chọn) Nếu chạy trên Linux, bạn có thể mount trực tiếp file localtime của máy host:
      # - /etc/localtime:/etc/localtime:ro 

networks:
  default:
    name: hikari_network